apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-cg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cg
  template:
    metadata:
      labels:
        app: flask-cg
    spec:
      containers:
      - name: flask-cg
        image: flask-cg:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cg-service
spec:
  selector:
    app: flask-cg
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
